name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Value
      id: value
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Value
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          tests/value.c
        input: ''
        expected-output: '1'
        comparison-method: contains
        timeout: 10
        max-score: 1
    - name: sample1
      id: sample1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: sample1
        setup-command: ''
        command: javac -cp utilities/antlr-4.13.1-complete.jar -d out $(find src gen
          -name "*.java") && java -cp out:utilities/antlr-4.13.1-complete.jar SimpleLang
          samples/sample1.slc
        input: ''
        expected-output: |-
          New Scope: first_func
          Declared variable: apple
          Used variable: apple
          Used variable: apple
          New Scope: second_func
          Declared variable: banana
          Used variable: banana
          Used variable: three
          Used variable: banana
          New Scope: Main
          Declared variable: test
          Used variable: test
          Declared variable: tmp
          Used variable: tmp
          Called function: second_func
          Called function: first_func
          1
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        VALUE_RESULTS: "${{steps.value.outputs.result}}"
        SAMPLE1_RESULTS: "${{steps.sample1.outputs.result}}"
      with:
        runners: value,sample1
